<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRw6xfIu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRw6xfIu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRw6xfIu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRw6xfIu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRw6xfIu\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rw6xfIu',
    'container.build_id' => '3e14d613',
    'container.build_time' => 1613744487,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRw6xfIu');
